swipe:
  3:
    left:
      command: 'xdotool key alt+Left'
    right:
      command: 'xdotool key alt+Right'
    up:
      command: 'xdotool key alt+F1'
    down:
      command: 'xdotool key alt+F1'
  4:
    left:
      command: 'xdotool key ctrl+alt+Down'
    right:
      command: 'xdotool key ctrl+alt+Up'
    up:
      command: 'xdotool key ctrl+alt+Down'
    down:
      command: 'xdotool key ctrl+alt+Up'
pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
    command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
